# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
        migrations.RemoveField(
            model_name='email',
            name='created_date',
        ),
    ]
