# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_email_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.TextField(),
        ),
    ]
