# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170313_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.CharField(max_length=4000),
        ),
    ]
